### ISSUE TITLE
Add dismiss button in CampaignNotificationBuilder

### ISSUE THREAD

**Issue by LewisRhine** [RadiusNetworks/campaignkit-android#3]
Add a dismiss or the option to add a dismiss button to `CampaignNotificationBuilder`

**Comment by cupakromer** [comment]
Thanks for the suggestion @LewisRhine. We've added this to our roadmap for future improvements.

**Comment by cupakromer** [comment]
This will be available in the next release. There will now be a `CampaignNotificationBuilder#setCancelable(boolean)` option. It will default to `false` but calling this with `true` will add the standard "Cancel" button.

**Comment by cupakromer** [comment]
This is now available in [version 0.12.0](https://github.com/RadiusNetworks/campaignkit-android/releases/tag/0.12.0).
