### ISSUE TITLE
Timeout Exception 

### ISSUE THREAD

**Issue by AhmedAshrafSaleh** [RadiusNetworks/campaignkit-android#6]
We have face a timeout exception when using the campaign kit library. However we can not reproduce from the dev side. Here is the exception:

```
Fatal Exception: java.util.concurrent.TimeoutException: java.util.regex.Matcher.finalize() timed out after 30 seconds
       at java.util.regex.Matcher.closeImpl(Matcher.java)
       at java.util.regex.Matcher.finalize(Matcher.java:527)
       at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:202)
       at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:185)
       at java.lang.Thread.run(Thread.java:833)
```

and here is the screen shoot for the stack:
<img width="754" alt="screen shot 2017-01-26 at 2 59 20 pm" src="https://cloud.githubusercontent.com/assets/7487812/22332151/125613b2-e3d8-11e6-8559-33c920b6f20b.png">

**Comment by cupakromer** [comment]
How often is this occurring?

Are you seeing an ANR ("Application Not Responding") dialog when this occurs?

I don't see any obvious reason for this. The only thing I can think of is the processing is happening on the main thread. If the phone is busy it's possible this process slows down enough to trigger something.
