### ISSUE TITLE
Android O - Failed attempting to start service: BeaconIntentProcessor

### ISSUE THREAD

**Issue by shekibobo** [RadiusNetworks/campaignkit-android#8]
I'm seeing this error when background geofence scanning is running on Android Oreo devices.

I found this related issue in another beacon library: https://github.com/AltBeacon/android-beacon-library/issues/547 and their solution https://github.com/AltBeacon/android-beacon-library/pull/484.

**Comment by cupakromer** [comment]
Thanks for reporting this. Are you seeing this issue only related to geofences or is it also affecting beacon scanning?

**Comment by shekibobo** [comment]
I've only seen the background scanning work recently while testing geofencing, but bluetooth is enabled and is also scanning. It's likely caused by both.

**Comment by cupakromer** [comment]
This is fixed in the latest [version 0.14.0 release](https://github.com/RadiusNetworks/campaignkit-android/releases/tag/0.14.0).
