### ISSUE TITLE
Android O - Notifications are not displayed.

### ISSUE THREAD

**Issue by shekibobo** [RadiusNetworks/campaignkit-android#9]
Notifications on devices running Android Oreo are not displayed because they are not created with a channel id.

**Comment by cupakromer** [comment]
Thanks for reporting this. We're taking a look what other changes need to be made to support Android O. Can you confirm you are reporting this issue for the built-in notification builder [`CampaignNotificationBuilder`](http://developer.radiusnetworks.com/campaignkit/android/javadocs/0.13.0/com/radiusnetworks/campaignkit/CampaignNotificationBuilder.html)?

**Comment by shekibobo** [comment]
Yes, that's the issue. I've managed to write my own wrapper that builds the notification using channels, but the default does not work on Android O.

**Comment by cupakromer** [comment]
This is fixed in the latest [version 0.14.0 release](https://github.com/RadiusNetworks/campaignkit-android/releases/tag/0.14.0).
